### ISSUE TITLE
Reducer cases with constants

### ISSUE THREAD

**Issue by leslie-alldridge** [rebeccajackson/parttime-gardener#1]
Exporting constants for the reducers can be used in place of strings e.g. 'LOAD_USER_VEGES'

**Comment by rebeccajackson** [comment]
#1  Thanks for bringing that to my attention, I've updated the code to follow that format

**Comment by leslie-alldridge** [comment]
Looks fab, for multiple reducers sometimes we'll see a file/folder called constants and it will just have the sole purpose of defining and exporting many constants. but what you've done looks sweet as.
